#!/usr/bin/env node

var fs = require('fs'),
path = require('path'),
connect = require('connect'),
ejs = require('ejs'),
port = process.env.PORT || 9876,
app,

o = {}, 
date = new Date(),
posts = path.join(__dirname, '../src/components/bolddaemon/posts.json');

fs.readFile(posts, function(e,d) {

	if (e) {
		throw e;
	}

	posts = JSON.parse(d);
});

o.title = '';
o.body = '';
o.date = date.getFullYear() + '-' + (date.getMonth()+1) + '-' + date.getDate();

console.log('Listening on %d for editing! %s', port, 'http://localhost:' + port);

app = connect()
	.use(connect.logger('dev'))
	.use(connect.bodyParser())
	.use(function(req, res) {
		if (req.url === '/') {
			fs.readFile('editor/editor.ejs', 'utf8', function(e, d) {
				d = ejs.render(d, {posts:posts});
				res.setHeader('Content-Type', 'text/html');
				res.end(d);
			});
		}
		if (req.url === '/edit') {
		}
		if (req.url === '/save') {
			console.log(req.body);
			res.end();
		}
	});

app.listen(port, 'localhost');
